[project]
name = "polars-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.14.0",
    "jupyter>=1.1.1",
    "polars>=1.30.0",
]

[tool.setuptools.packages.find]
where = ["src"]
